"""Change storm_id to String type

Revision ID: b5ce7c350237
Revises: 
Create Date: 2025-11-18 21:03:02.468238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ce7c350237'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Drop foreign key constraints first
    op.drop_constraint('damage_assessment_storm_id_fkey', 'damage_assessment', type_='foreignkey')
    op.drop_constraint('news_sources_storm_id_fkey', 'news_sources', type_='foreignkey')
    op.drop_constraint('rescue_requests_storm_id_fkey', 'rescue_requests', type_='foreignkey')
    op.drop_constraint('social_posts_storm_id_fkey', 'social_posts', type_='foreignkey')
    op.drop_constraint('storm_tracks_storm_id_fkey', 'storm_tracks', type_='foreignkey')
    
    # Drop the primary key constraint and sequence
    op.execute('ALTER TABLE storms DROP CONSTRAINT storms_pkey')
    op.execute('DROP SEQUENCE IF EXISTS storms_storm_id_seq CASCADE')
    
    # Change column types
    op.alter_column('storms', 'storm_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('storms', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('storms', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    
    # Re-add primary key
    op.create_primary_key('storms_pkey', 'storms', ['storm_id'])
    
    # Change foreign key columns
    op.alter_column('damage_assessment', 'storm_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('news_sources', 'storm_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('rescue_requests', 'storm_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('social_posts', 'storm_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    
    # Create enum type first
    sa.Enum('TWITTER', 'FACEBOOK', 'TIKTOK', 'UNKNOWN', name='sourceenum').create(op.get_bind(), checkfirst=True)
    
    op.alter_column('social_posts', 'source',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('TWITTER', 'FACEBOOK', 'TIKTOK', 'UNKNOWN', name='sourceenum'),
               existing_nullable=True,
               postgresql_using='source::sourceenum')
    op.alter_column('storm_tracks', 'storm_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    
    # Re-create foreign key constraints
    op.create_foreign_key('damage_assessment_storm_id_fkey', 'damage_assessment', 'storms', ['storm_id'], ['storm_id'])
    op.create_foreign_key('news_sources_storm_id_fkey', 'news_sources', 'storms', ['storm_id'], ['storm_id'])
    op.create_foreign_key('rescue_requests_storm_id_fkey', 'rescue_requests', 'storms', ['storm_id'], ['storm_id'])
    op.create_foreign_key('social_posts_storm_id_fkey', 'social_posts', 'storms', ['storm_id'], ['storm_id'])
    op.create_foreign_key('storm_tracks_storm_id_fkey', 'storm_tracks', 'storms', ['storm_id'], ['storm_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('storms', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('storms', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('storms', 'storm_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('storm_tracks', 'storm_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('social_posts', 'source',
               existing_type=sa.Enum('TWITTER', 'FACEBOOK', 'TIKTOK', 'UNKNOWN', name='sourceenum'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('social_posts', 'storm_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('rescue_requests', 'storm_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('news_sources', 'storm_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('damage_assessment', 'storm_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
