"""Update news_sources table

Revision ID: d1b5326d6e03
Revises: b5ce7c350237
Create Date: 2025-11-20 22:50:23.357842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b5326d6e03'
down_revision: Union[str, Sequence[str], None] = 'b5ce7c350237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_sources', sa.Column('thumbnail_url', sa.Text(), nullable=True))
    op.add_column('news_sources', sa.Column('category', sa.Text(), nullable=True))
    op.drop_column('news_sources', 'damage_estimate')
    op.drop_column('news_sources', 'fatalities')
    op.drop_column('news_sources', 'injured')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_sources', sa.Column('injured', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('news_sources', sa.Column('fatalities', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('news_sources', sa.Column('damage_estimate', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('news_sources', 'category')
    op.drop_column('news_sources', 'thumbnail_url')
    # ### end Alembic commands ###
